name: Server Mine (Archlinux)

on:
  workflow_dispatch

env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  ci:
    runs-on: ubuntu-latest

    container:
      image: archlinux
      options: --privileged

    steps:
      - name: Install Packages.
        run: |
          pacman -Syu --noconfirm
          pacman -S git sudo base-devel util-linux procps-ng --noconfirm

      - name: Clone Repo Server-Mine
        uses: MoeKernel/github-repo-action@v3.1
        with:
          depth: 1
          branch: 'main'
          owner: 'whyakari'
          repository: 'server-mine'
          access-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Github Configs
        working-directory: ./server-mine
        run: |
          git config --global user.email "akariondev@gmail.com"
          git config --global user.name "ginkgo"
  
      - name: Install Dependencies
        run: |
         pacman -Syu --noconfirm
         pacman -S --noconfirm base-devel jdk8-openjdk

      - name: Get Paper
        working-directory: ./server-mine
        run: |
          url='https://api.papermc.io/v2/projects/paper/versions/1.8.8/builds/445/downloads/paper-1.8.8-445.jar'
          wget -O minecraft_server.jar $url

      - name: Set Permission 
        working-directory: ./server-mine
        run: |
          chmod +x minecraft_server.jar

      - name: Start Server
        working-directory: ./server-mine
        run: |
          ram=5G # Set the RAM here.
          java -Xmx$ram -Xms$ram -jar minecraft_server.jar nogui
          
      - name: Agree to the EULA
        working-directory: ./server-mine
        run: |
          sed -i '3s/false/true/' eula.txt

      - name: Start Server (finally)
        working-directory: ./server-mine
        run: |
          ram=5G # Set the RAM here.
          java -Xmx$ram -Xms$ram -jar minecraft_server.jar nogui
